### PR TITLE
Fix stacktrace issues on Windows

### LINKED ISSUE #101: Rust-Based Stack Traces Corrupt When Tracy Enabled
A real doozy of an issue here. I honestly don't know if this is a rust_tracy_client problem, a backtrace-rs problem, or a tracy problem, I'm starting here as a first line of action.

Clone this repository: https://github.com/cwfitzgerald/tracy-client-stacktrace-issue on a machine running Windows.

---

`cargo run` returns a stacktrace like normal. This is basically just a program which instantly panics.

<details>
<summary>Normal Stacktrace</summary>

```
thread 'main' panicked at src\main.rs:5:5:
Hello, world!
stack backtrace:
   0:     0x7ff7e03f65ba - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:99
   1:     0x7ff7e03f65ba - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7e03f65ba - std::sys_common::backtrace::_print_fmt
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common\backtrace.rs:68
   3:     0x7ff7e03f65ba - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff7e04048ab - core::fmt::rt::Argument::fmt
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\fmt\rt.rs:142
   5:     0x7ff7e04048ab - core::fmt::write
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\fmt\mod.rs:1153
   6:     0x7ff7e03f4a81 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\io\mod.rs:1843
   7:     0x7ff7e03f63a6 - std::sys_common::backtrace::print
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff7e03f83df - std::panicking::default_hook::closure$1
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:272
   9:     0x7ff7e03f8077 - std::panicking::default_hook
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:292
  10:     0x7ff7e03f891d - std::panicking::rust_panic_with_hook
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:779
  11:     0x7ff7e03f879b - std::panicking::begin_panic_handler::closure$0
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:649
  12:     0x7ff7e03f6c49 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common\backtrace.rs:171
  13:     0x7ff7e03f8496 - std::panicking::begin_panic_handler
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
  14:     0x7ff7e04097f7 - core::panicking::panic_fmt
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
  15:     0x7ff7e03f12ff - tracy_client_stacktrace::main
                               at F:\Programming\tracy-client-stacktrace\src\main.rs:5
  16:     0x7ff7e03f119b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\ops\function.rs:250
  17:     0x7ff7e03f136e - core::hint::black_box
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\hint.rs:337
  18:     0x7ff7e03f136e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\sys_common\backtrace.rs:155
  19:     0x7ff7e03f1291 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\rt.rs:166
  20:     0x7ff7e03f2f42 - std::rt::lang_start_internal
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\rt.rs:148
  21:     0x7ff7e03f126a - std::rt::lang_start<tuple$<> >
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\rt.rs:165
  22:     0x7ff7e03f1319 - main
  23:     0x7ff7e0407ff0 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  24:     0x7ff7e0407ff0 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  25:     0x7ff8dc9a257d - BaseThreadInitThunk
  26:     0x7ff8dd5caa48 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\tracy-client-stacktrace.exe` (exit code: 101)
```

</details>

---

`cargo run --features enable` now turns on tracy_client, then panics. Pulls a completely nonsensical stacktrace.

<details>
<summary>Nonsense</summary>

```
thread 'main' panicked at src\main.rs:5:5:
Hello, world!
stack backtrace:
   0:     0x7ff615a8703a - <unknown>
   1:     0x7ff615a9532b - <unknown>
   2:     0x7ff615a85501 - <unknown>
   3:     0x7ff615a86e26 - <unknown>
   4:     0x7ff615a88e5f - <unknown>
   5:     0x7ff615a88af7 - <unknown>
   6:     0x7ff615a8939d - <unknown>
   7:     0x7ff615a8921b - <unknown>
   8:     0x7ff615a876c9 - <unknown>
   9:     0x7ff615a88f16 - <unknown>
  10:     0x7ff615abfd67 - <unknown>
  11:     0x7ff615a812e4 - <unknown>
  12:     0x7ff615a811ab - <unknown>
  13:     0x7ff615a8110e - <unknown>
  14:     0x7ff615a81371 - <unknown>
  15:     0x7ff615a839c2 - <unknown>
  16:     0x7ff615a8134a - <unknown>
  17:     0x7ff615a81309 - <unknown>
  18:     0x7ff615abddac - <unknown>
  19:     0x7ff8dc9a257d - BaseThreadInitThunk
  20:     0x7ff8dd5caa48 - RtlUserThreadStar
```

</details>

---

If I run this in the visual studio debugger with Break on All C++ exceptions enabled, visual studio gives a sane backtrace, so the stack itself seems correct.

<details>
<summary>VS Backtrace</summary>

```
 	KernelBase.dll!RaiseException()	Unknown
>	vcruntime140.dll!_CxxThrowException(void * pExceptionObject, const _s__ThrowInfo * pThrowInfo) Line 75	C++
 	[Inline Frame] tracy-client-stacktrace.exe!panic_unwind::real_imp::panic() Line 323	Unknown
 	tracy-client-stacktrace.exe!panic_unwind::__rust_start_panic() Line 106	Unknown
 	tracy-client-stacktrace.exe!std::panicking::rust_panic() Line 831	Unknown
 	tracy-client-stacktrace.exe!std::panicking::rust_panic_with_hook() Line 801	Unknown
 	tracy-client-stacktrace.exe!std::panicking::begin_panic_handler::closure$0() Line 658	Unknown
 	tracy-client-stacktrace.exe!std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>() Line 171	Unknown
 	tracy-client-stacktrace.exe!std::panicking::begin_panic_handler() Line 645	Unknown
 	tracy-client-stacktrace.exe!core::panicking::panic_fmt() Line 72	Unknown
 	tracy-client-stacktrace.exe!tracy_client_stacktrace::main() Line 5	Unknown
 	tracy-client-stacktrace.exe!core::ops::function::FnOnce::call_once<void (*)(),tuple$<>>(void(*)()) Line 250	Unknown
 	[Inline Frame] tracy-client-stacktrace.exe!core::hint::black_box(tuple$<>) Line 155	Unknown
 	tracy-client-stacktrace.exe!std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<>>(void(*)() f) Line 161	Unknown
 	tracy-client-stacktrace.exe!std::rt::lang_start::closure$0<tuple$<>>(std::rt::lang_start::closure_env$0<tuple$<>> *) Line 166	Unknown
 	tracy-client-stacktrace.exe!std::rt::lang_start_internal() Line 148	Unknown
 	tracy-client-stacktrace.exe!std::rt::lang_start<tuple$<>>(void(*)() main, __int64 argc, unsigned char * * argv, unsigned char sigpipe) Line 165	Unknown
 	tracy-client-stacktrace.exe!main()	Unknown
 	[Inline Frame] tracy-client-stacktrace.exe!invoke_main() Line 78	C++
 	tracy-client-stacktrace.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```

</details>

This happens with all features disabled, only `enable`. This example uses `manual-lifetime`, but this happens without.

### PR DESCRIPTION
**Pull request by Timbals**
There are 2 issues with capturing stack traces on Windows.
Specifically with the resolving of the symbols of the stack traces.
Note that this affects both the stack traces captured by Rust and Tracy.

Both Rust and Tracy use the `dbghelp.dll` symbol helper to resolve symbols.
The first issue is that `dbghelp.dll` is single threaded and all its functions need to be externally synchronized.
Rust uses a [named Windows mutex to synchronize](https://github.com/rust-lang/backtrace-rs/blob/4f3acf7a0a9f686ec004716e5d514d9732b41486/src/dbghelp.rs#L253) access to `dbghelp.dll` between the standard library and the `backtrace-rs` crate when both are used.
The first commit in this PR makes Tracy use the same named Mutex.
Not properly synchronizing can lead to partially corrupted stacktraces.
<details>
<summary>Example corrupted stacktrace</summary>

Note the `<unknown>` at the top probably caused by some race condition
```
stack backtrace:
   0:     0x7ff7a900767d - <unknown>
   1:     0x7ff7a9014bc9 - <unknown>
   2:     0x7ff7a9006011 - <unknown>
   3:     0x7ff7a90093c7 - <unknown>
   4:     0x7ff7a9008fb9 - <unknown>
   5:     0x7ff7a9009a72 - <unknown>
   6:     0x7ff7a900990f - <unknown>
   7:     0x7ff7a9007d6f - <unknown>
   8:     0x7ff7a9009526 - <unknown>
   9:     0x7ff7a903dbc4 - <unknown>
  10:     0x7ff7a90012ee - tracy_client_stacktrace::main
                               at C:\Dev\tracy-client-stacktrace-issue\src\main.rs:5
  11:     0x7ff7a900138b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\ops\function.rs:250
  12:     0x7ff7a900142e - core::hint::black_box
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\hint.rs:389
  13:     0x7ff7a900142e - std::sys::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\std\src\sys\backtrace.rs:152
  14:     0x7ff7a9001401 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\std\src\rt.rs:162
  15:     0x7ff7a9004279 - std::rt::lang_start_internal::closure$2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\rt.rs:141
  16:     0x7ff7a9004279 - std::panicking::try::do_call
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:557
  17:     0x7ff7a9004279 - std::panicking::try
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:521
  18:     0x7ff7a9004279 - std::panic::catch_unwind
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panic.rs:350
  19:     0x7ff7a9004279 - std::rt::lang_start_internal
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\rt.rs:141
  20:     0x7ff7a90013da - std::rt::lang_start<tuple$<> >
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\std\src\rt.rs:161
  21:     0x7ff7a9001309 - main
  22:     0x7ff7a903b918 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  23:     0x7ff7a903b918 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  24:     0x7ffaad70257d - BaseThreadInitThunk
  25:     0x7ffaae1eaf28 - RtlUserThreadStart
```
</details>

The second issue is that Rust and Tracy initialize the symbol helper in different ways.
Since Rust 1.78.0 the compiler no longer includes absolute paths to .pdb files in the binary (https://github.com/rust-lang/rust/pull/121297). That can make the symbol resolution fail because by default only the current working directory is searched for .pdb files.
There was also a corresponding PR to `backtrace-rs` to include the executable location in the search path (https://github.com/rust-lang/backtrace-rs/pull/584), but when Tracy initializes `dbghelp.dll` first, the modules get loaded before the search path gets modified.
The second commit in this PR fixes that by capturing and resolving a backtrace using the standard library before Tracy does the initialization.
This fixes #101.

### CODE REVIEW

File: tracy-client-sys/src/dbghelp.rs [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+/// and because there is no cleanup function, the handle is leaked.
+static RUST_BACKTRACE_MUTEX: AtomicPtr<core::ffi::c_void> = AtomicPtr::new(std::ptr::null_mut());
+
+#[no_mangle]
+extern "C" fn RustBacktraceMutexInit() {
+    unsafe {
+        // Initialize the `dbghelp.dll` symbol helper by capturing and resolving a backtrace using the standard library.
+        // Since symbol resolution is lazy, the backtrace is written to `sink`, which forces symbol resolution.
+        // Refer to the module documentation on why the standard library should do the initialization instead of Tracy.
+        write!(sink(), "{:?}", std::backtrace::Backtrace::force_capture()).unwrap();
```
Comment (nagisa) [inline tracy-client-sys/src/dbghelp.rs:48]: Could we avoid the `unwrap` here? Although it is very likely that writing a backtrace to a `sink()` cannot fail at all, ever, just in case there is some perverse corner case, I would rather users deal with broken stack traces than the program failing completely in that scenario.

File: tracy-client-sys/src/dbghelp.rs [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+
+        // The name is the same one that the standard library and `backtrace-rs` use
+        let mut name = [0; 33];
```
Comment (nagisa) [inline tracy-client-sys/src/dbghelp.rs:51]:
```suggestion
        let mut name: [u8; 33] = *b"Local\\RustBacktraceMutexFFFFFFFF\0";
```

makes it a little more obvious that 33 is indeed sufficient (and exact) size required.

File: tracy-client-sys/src/dbghelp.rs [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+
+        // Creates a named mutex that is shared with the standard library and `backtrace-rs`
+        // to synchronize access to `dbghelp.dll` functions, which are single threaded.
+        let mutex = CreateMutexA(None, FALSE, name).unwrap();
+        assert!(!mutex.is_invalid());
+
+        // Initialization of the `dbghelp.dll` symbol helper should have already happened
+        // through the standard library backtrace above.
+        // Therefore, the shared named mutex should already have existed.
+        assert_eq!(GetLastError(), ERROR_ALREADY_EXISTS);
```
Comment (nagisa) [inline tracy-client-sys/src/dbghelp.rs:64]: I'd `debug_assert_eq` this for the similar reasons as above (in case `libstd` stops creating this Mutex, if it just so happened that the dbghelp no longer needed any locks to work.)

**Review by nagisa — COMMENTED** [review]
Thank you for looking into this and getting to the bottom of the problem!

Perhaps the one thing I'm somewhat iffy about is the dependency on `windows` here. I think this and `windows-sys` are outsized dependencies for the `tracy-client-sys` crate. Given the limited use of the APIs, could this perhaps be changed to use `windows-targets` instead? Some of my thoughts on the `windows{,-sys}` dependency are [here](https://github.com/nagisa/rust_libloading/pull/125#discussion_r1244321694). You can also find some inspiration for the changes here at that same link.

It is fine if you don't have the time or capacity for such a change -- I'll just get around to it myself at some point in the future before I cut the next release.

File: tracy-client-sys/src/dbghelp.rs (hunk 1 above)
Comment (Timbals) [reply tracy-client-sys/src/dbghelp.rs]: The result is ignored now. This is only called to trigger a symbol resolve in the standard library, so the result doesn't matter.

File: tracy-client-sys/src/dbghelp.rs (hunk 2 above)
Comment (Timbals) [reply tracy-client-sys/src/dbghelp.rs]: It uses `format!` directly now. I initially adapted this from the implementation in `backtrace-rs` which seems to avoid allocations, but that is not necessary here.

File: tracy-client-sys/src/dbghelp.rs (hunk 3 above)
Comment (Timbals) [reply tracy-client-sys/src/dbghelp.rs]: I changed the error handling, and it will no longer panic should the standard library change its symbol resolution logic.

**Review by nagisa — APPROVED** [review]
